### ISSUE TITLE
esrg css doesn't validate..

### ISSUE THREAD

**Issue by tekbasse** [johnpolacek/extra-strength-responsive-grids#3]
Hi, I really appreciate the work done producing ESRG. 

However, when I add some simple css (changing font-size etc) on a project I'm working on, browsers mostly ignore all but basic css changes.

Could the issue be related to browsers silently ignoring css extending from broken css?

The w3 css validator on http://dfcb.github.io/extra-strength-responsive-grids/ shows 18 css validation errors. I doubt the vendor extension warnings are an issue.

normalize.css does not show any validation issues with w3 css validator.

**Comment by johnpolacek** [comment]
In the grid.css file, which is really the only thing that matters for people who want to use ESRG, there are 4 errors and they are all because of the IE fallback for box-sizing:border-box 

I could get into the various validation errors for main.css, but those are just for the demo page and are mostly IE related.

**Comment by tekbasse** [comment]
Hi, Just wanted to note some good news for anyone that cares about validating the css:

Removing the _behavior and the Microsoft references to *DX_ is about all it takes to validate. 

The removed css only affects IE and doesn't appear to be anything that affects function. It just degrades some display aspect of IE, where IE doesn't follow css web standards anyway..

holiday cheers!
